// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kick.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KickMsg struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	KickType             int32    `protobuf:"varint,2,opt,name=kickType,proto3" json:"kickType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickMsg) Reset()         { *m = KickMsg{} }
func (m *KickMsg) String() string { return proto.CompactTextString(m) }
func (*KickMsg) ProtoMessage()    {}
func (*KickMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_56cd565312cd19f9, []int{0}
}

func (m *KickMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickMsg.Unmarshal(m, b)
}
func (m *KickMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickMsg.Marshal(b, m, deterministic)
}
func (m *KickMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickMsg.Merge(m, src)
}
func (m *KickMsg) XXX_Size() int {
	return xxx_messageInfo_KickMsg.Size(m)
}
func (m *KickMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KickMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KickMsg proto.InternalMessageInfo

func (m *KickMsg) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *KickMsg) GetKickType() int32 {
	if m != nil {
		return m.KickType
	}
	return 0
}

type KickAnswer struct {
	Kicked               bool     `protobuf:"varint,1,opt,name=kicked,proto3" json:"kicked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickAnswer) Reset()         { *m = KickAnswer{} }
func (m *KickAnswer) String() string { return proto.CompactTextString(m) }
func (*KickAnswer) ProtoMessage()    {}
func (*KickAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_56cd565312cd19f9, []int{1}
}

func (m *KickAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickAnswer.Unmarshal(m, b)
}
func (m *KickAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickAnswer.Marshal(b, m, deterministic)
}
func (m *KickAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickAnswer.Merge(m, src)
}
func (m *KickAnswer) XXX_Size() int {
	return xxx_messageInfo_KickAnswer.Size(m)
}
func (m *KickAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_KickAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_KickAnswer proto.InternalMessageInfo

func (m *KickAnswer) GetKicked() bool {
	if m != nil {
		return m.Kicked
	}
	return false
}

func init() {
	proto.RegisterType((*KickMsg)(nil), "protos.KickMsg")
	proto.RegisterType((*KickAnswer)(nil), "protos.KickAnswer")
}

func init() {
	proto.RegisterFile("kick.proto", fileDescriptor_56cd565312cd19f9)
}

var fileDescriptor_56cd565312cd19f9 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xce, 0x4c, 0xce,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0xb6, 0x5c, 0xec, 0xde,
	0x99, 0xc9, 0xd9, 0xbe, 0xc5, 0xe9, 0x42, 0x62, 0x5c, 0x6c, 0xa5, 0xc5, 0xa9, 0x45, 0x9e, 0x29,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e, 0x90, 0x14, 0x17, 0x07, 0x48, 0x63, 0x48,
	0x65, 0x41, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x9c, 0xaf, 0xa4, 0xc2, 0xc5, 0x05,
	0xd2, 0xee, 0x98, 0x57, 0x5c, 0x9e, 0x5a, 0x04, 0x32, 0x01, 0x24, 0x93, 0x0a, 0x31, 0x81, 0x23,
	0x08, 0xca, 0x4b, 0x82, 0x58, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x64, 0x4c, 0xc8,
	0x81, 0x00, 0x00, 0x00,
}
